commentConfiguration:
  preamble: '[CodeMention](https://github.com/tobyhs/codemention):'
  epilogue: Test Epilogue

rules:
  - patterns: ['src/**']
    mentions: ['tobyhs']
  - patterns: ['test/**']
    mentions: ['epr-tester']
