#!/usr/bin/env bash

set -euo pipefail

: "${CODEMENTION_BRANCH:=main}"
BASE_BRANCH="$(git branch --show-current)"
TIMESTAMP="$(date -u +%Y%m%d%H%M%S)"
BRANCH="dnm-test-${TIMESTAMP}"

git checkout -b "$BRANCH"

if [ "$CODEMENTION_BRANCH" != 'main' ]; then
  sed -i "s|\(uses: tobyhs/codemention@\).*|\1${CODEMENTION_BRANCH}|" .github/workflows/codemention.yml
  git add .github/workflows/codemention.yml
fi

echo "$TIMESTAMP" > src/testing
echo "$TIMESTAMP" > test/testing
git add src/testing test/testing
git commit -m "[DNM] Testing - ${TIMESTAMP}"
git push -u origin "$BRANCH"
gh pr create --base "$BASE_BRANCH" --fill
