name: codemention

on:
  # In typical usages of codemention, this should be pull_request_target
  # instead of pull_request. However, I'm using pull_request for convenience to
  # test other branches of codemention in the create-test-pr workflow.
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  codemention:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: tobyhs/codemention@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: node --version
