name: codemention

on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review]

jobs:
  codemention:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo Testing
      - run: node --version
      - uses: tobyhs/codemention@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
