name: Create Test PR

on: workflow_dispatch

jobs:
  create_test_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "noreply@example.com"
      - run: ./scripts/create-test-pr
        env:
          # Need a PAT because using secrets.GITHUB_TOKEN will not trigger
          # other workflow runs
          # (https://docs.github.com/en/actions/concepts/security/github_token#when-github_token-triggers-workflow-runs)
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
