name: Create Test PR

on:
  workflow_dispatch:
    inputs:
      codemention_branch:
        description: 'codemention branch to test'
        required: true
        type: string
        default: main

jobs:
  create_test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Need a PAT because pushing changes to files inside
          # .github/workflows/ requires the workflows permission and the
          # workflows permission can't be declared in a workflow file
          token: ${{ secrets.GH_PAT }}
      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "noreply@example.com"
      - run: ./scripts/create-test-pr
        env:
          CODEMENTION_BRANCH: ${{ inputs.codemention_branch }}
          # Need a PAT because using secrets.GITHUB_TOKEN will not trigger
          # other workflow runs
          # (https://docs.github.com/en/actions/concepts/security/github_token#when-github_token-triggers-workflow-runs)
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
